#!/usr/bin/env python3
"""
Champion Battery — test each candidate archetype as a STANDALONE strategy.

For each candidate, generates a config variant (all other archetypes disabled,
bypass_threshold=false → production threshold enforcement) and runs the v11
standalone backtester across consistency windows:

  full     2020-01-01 → 2024-12-31
  y2020..y2024   per calendar year
  wfo_train      2020-01-01 → 2022-12-31
  wfo_oos_2023   2023-01-01 → 2023-12-31
  wfo_oos_2024   2024-01-01 → 2024-12-31

Scorecard criteria (a champion must pass ALL):
  C1  positive PnL every calendar year (incl. bear 2022)
  C2  OOS PF >= 1.3 in 2023 AND 2024
  C3  train PF >= 1.3 AND train/OOS co-move (both profitable)
  C4  n >= 30 trades per OOS window
  C5  standalone MaxDD <= 10%

CPCV is run separately on survivors only (scripts/champion/run_cpcv.py).

Usage:
  python3 scripts/champion/run_battery.py                       # all 4 candidates
  python3 scripts/champion/run_battery.py --candidates liquidity_sweep
  python3 scripts/champion/run_battery.py --dry-run             # print plan only
"""

import argparse
import json
import subprocess
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parents[2]
BASE_CONFIG = REPO / "configs/bull_machine_isolated_v11_fixed.json"
OUT_ROOT = REPO / "results/champion"
CONFIG_DIR = REPO / "configs/champion"

ALL_ARCHETYPES = [
    "confluence_breakout", "exhaustion_reversal", "failed_continuation",
    "funding_divergence", "fvg_continuation", "liquidity_compression",
    "liquidity_sweep", "liquidity_vacuum", "long_squeeze", "oi_divergence",
    "order_block_retest", "retest_cluster", "spring", "trap_within_trend",
    "volume_fade_chop", "whipsaw", "wick_trap",
]

DEFAULT_CANDIDATES = ["liquidity_sweep", "trap_within_trend", "wick_trap", "spring"]

WINDOWS = {
    "full":         ("2020-01-01", "2024-12-31"),
    "y2020":        ("2020-01-01", "2020-12-31"),
    "y2021":        ("2021-01-01", "2021-12-31"),
    "y2022":        ("2022-01-01", "2022-12-31"),
    "y2023":        ("2023-01-01", "2023-12-31"),
    "y2024":        ("2024-01-01", "2024-12-31"),
    "wfo_train":    ("2020-01-01", "2022-12-31"),
}
# OOS windows reuse y2023/y2024 results — no duplicate runs.

BACKTEST_ARGS = ["--commission-rate", "0.0002", "--slippage-bps", "3",
                 "--initial-cash", "100000"]


def make_variant_config(candidate) -> Path:
    """Write a config variant: only `candidate` (str or list) enabled, thresholds enforced."""
    enabled = [candidate] if isinstance(candidate, str) else list(candidate)
    candidate = "__".join(enabled)
    cfg = json.loads(BASE_CONFIG.read_text())
    cfg["disabled_archetypes"] = [a for a in ALL_ARCHETYPES if a not in enabled]
    af = cfg.setdefault("adaptive_fusion", {})
    af["bypass_threshold"] = False
    af["_champion_note"] = (
        f"AUTO-GENERATED by run_battery.py — standalone test of {candidate}. "
        "All other archetypes disabled; production threshold enforcement."
    )
    CONFIG_DIR.mkdir(parents=True, exist_ok=True)
    path = CONFIG_DIR / f"champion_{candidate}.json"
    path.write_text(json.dumps(cfg, indent=2))
    return path


def run_window(candidate: str, config_path: Path, window: str,
               start: str, end: str) -> dict:
    out_dir = OUT_ROOT / candidate / window
    out_dir.mkdir(parents=True, exist_ok=True)
    stats_file = out_dir / "performance_stats.json"
    if stats_file.exists():
        print(f"  [skip] {candidate}/{window} (cached)")
        return json.loads(stats_file.read_text())

    cmd = [sys.executable, str(REPO / "bin/backtest_v11_standalone.py"),
           "--config", str(config_path),
           "--start-date", start, "--end-date", end,
           "--output-dir", str(out_dir)] + BACKTEST_ARGS
    print(f"  [run ] {candidate}/{window} ({start} → {end})")
    res = subprocess.run(cmd, capture_output=True, text=True, cwd=REPO)
    if res.returncode != 0:
        print(f"  [FAIL] {candidate}/{window}: rc={res.returncode}")
        print(res.stderr[-2000:])
        return {"error": res.returncode}
    if not stats_file.exists():
        print(f"  [FAIL] {candidate}/{window}: no performance_stats.json produced")
        return {"error": "no_stats"}
    return json.loads(stats_file.read_text())


def metric(stats: dict, *names, default=None):
    for n in names:
        if n in stats:
            return stats[n]
    return default


def score(candidate: str, results: dict) -> dict:
    """Apply C1–C5 to one candidate's window results."""
    def pnl(w):    return metric(results.get(w, {}), "total_pnl", "net_pnl", default=0.0)
    def pf(w):     return metric(results.get(w, {}), "profit_factor", default=0.0)
    def n(w):      return metric(results.get(w, {}), "total_trades", "num_trades", default=0)
    def mdd(w):
        v = metric(results.get(w, {}), "max_drawdown_pct", "max_drawdown", default=0.0)
        return abs(v)

    years = ["y2020", "y2021", "y2022", "y2023", "y2024"]
    c1 = bool(all(pnl(y) > 0 for y in years))
    c2 = bool(pf("y2023") >= 1.3 and pf("y2024") >= 1.3)
    c3 = bool(pf("wfo_train") >= 1.3 and pnl("wfo_train") > 0 and pnl("y2023") > 0 and pnl("y2024") > 0)
    c4 = bool(n("y2023") >= 30 and n("y2024") >= 30)
    c5 = bool(mdd("full") <= 10.0)

    return {
        "candidate": candidate,
        "criteria": {
            "C1_positive_every_year": c1,
            "C2_oos_pf_ge_1.3": c2,
            "C3_train_oos_comove": c3,
            "C4_oos_n_ge_30": c4,
            "C5_maxdd_le_10pct": c5,
        },
        "pass": all([c1, c2, c3, c4, c5]),
        "detail": {
            w: {"pnl": round(pnl(w)), "pf": round(pf(w), 2),
                "trades": n(w), "maxdd_pct": round(mdd(w), 1)}
            for w in results
        },
    }


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--candidates", nargs="+", default=DEFAULT_CANDIDATES)
    ap.add_argument("--dry-run", action="store_true")
    args = ap.parse_args()

    scorecards = []
    for cand in args.candidates:
        assert cand in ALL_ARCHETYPES, f"unknown archetype: {cand}"
        print(f"\n=== {cand} ===")
        cfg = make_variant_config(cand)
        if args.dry_run:
            print(f"  config: {cfg}")
            for w, (s, e) in WINDOWS.items():
                print(f"  window {w}: {s} → {e}")
            continue
        results = {}
        for w, (s, e) in WINDOWS.items():
            results[w] = run_window(cand, cfg, w, s, e)
        card = score(cand, results)
        scorecards.append(card)
        out = OUT_ROOT / cand / "scorecard.json"
        out.write_text(json.dumps(card, indent=2))
        print(f"  scorecard → {out}")
        for k, v in card["criteria"].items():
            print(f"    {'PASS' if v else 'FAIL'}  {k}")
        print(f"  OVERALL: {'PASS' if card['pass'] else 'FAIL'}")

    if scorecards:
        summary = OUT_ROOT / "battery_summary.json"
        summary.write_text(json.dumps(scorecards, indent=2))
        print(f"\n=== SUMMARY ({summary}) ===")
        print(f"{'candidate':<22}{'pass':<6}{'full_pnl':>10}{'full_pf':>8}{'2022_pnl':>10}{'oos23_pf':>9}{'oos24_pf':>9}")
        for c in scorecards:
            d = c["detail"]
            print(f"{c['candidate']:<22}{str(c['pass']):<6}"
                  f"{d.get('full', {}).get('pnl', 0):>10}{d.get('full', {}).get('pf', 0):>8}"
                  f"{d.get('y2022', {}).get('pnl', 0):>10}"
                  f"{d.get('y2023', {}).get('pf', 0):>9}{d.get('y2024', {}).get('pf', 0):>9}")


if __name__ == "__main__":
    main()
